// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go-000/Week04/internal/biz"
	"Go-000/Week04/internal/data"
	"Go-000/Week04/internal/service"
)

// Injectors from wire.go:

func InitProjectDemo() *biz.GirlsHandler {
	girlsDao := data.NewGirlsDao()
	girlsService := service.NewGirlsService(girlsDao)
	girlsHandler := biz.NewGirlsHandler(girlsService)
	return girlsHandler
}
