// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: girls.proto

package demo_v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//demo 请求
type GirlsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GirlsRequest) Reset() {
	*x = GirlsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_girls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GirlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GirlsRequest) ProtoMessage() {}

func (x *GirlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_girls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GirlsRequest.ProtoReflect.Descriptor instead.
func (*GirlsRequest) Descriptor() ([]byte, []int) {
	return file_girls_proto_rawDescGZIP(), []int{0}
}

func (x *GirlsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//demo 响应
type GirlsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GirlsResponse) Reset() {
	*x = GirlsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_girls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GirlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GirlsResponse) ProtoMessage() {}

func (x *GirlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_girls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GirlsResponse.ProtoReflect.Descriptor instead.
func (*GirlsResponse) Descriptor() ([]byte, []int) {
	return file_girls_proto_rawDescGZIP(), []int{1}
}

func (x *GirlsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_girls_proto protoreflect.FileDescriptor

var file_girls_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x69, 0x72, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x22, 0x0a, 0x0c, 0x47, 0x69, 0x72, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x47, 0x69,
	0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x47, 0x0a, 0x09, 0x47, 0x69, 0x72, 0x6c, 0x73, 0x44, 0x65,
	0x6d, 0x6f, 0x12, 0x3a, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x69, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x69, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_girls_proto_rawDescOnce sync.Once
	file_girls_proto_rawDescData = file_girls_proto_rawDesc
)

func file_girls_proto_rawDescGZIP() []byte {
	file_girls_proto_rawDescOnce.Do(func() {
		file_girls_proto_rawDescData = protoimpl.X.CompressGZIP(file_girls_proto_rawDescData)
	})
	return file_girls_proto_rawDescData
}

var file_girls_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_girls_proto_goTypes = []interface{}{
	(*GirlsRequest)(nil),  // 0: demo.v1.GirlsRequest
	(*GirlsResponse)(nil), // 1: demo.v1.GirlsResponse
}
var file_girls_proto_depIdxs = []int32{
	0, // 0: demo.v1.GirlsDemo.Request:input_type -> demo.v1.GirlsRequest
	1, // 1: demo.v1.GirlsDemo.Request:output_type -> demo.v1.GirlsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_girls_proto_init() }
func file_girls_proto_init() {
	if File_girls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_girls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GirlsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_girls_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GirlsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_girls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_girls_proto_goTypes,
		DependencyIndexes: file_girls_proto_depIdxs,
		MessageInfos:      file_girls_proto_msgTypes,
	}.Build()
	File_girls_proto = out.File
	file_girls_proto_rawDesc = nil
	file_girls_proto_goTypes = nil
	file_girls_proto_depIdxs = nil
}
